server:
  port: 8081

spring:
  jpa:
      show-sql: true
      database: mysql
      generate-ddl: false

  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost/sso
      username: root
      password:

